//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.8009
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=2.0.50727.3038.
// y módificado por huchim...! ¨:P
// 

namespace Cfe.Web.Portal
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "ServiceSoap", Namespace = "http://tempuri.org/")]
    internal partial class Designer : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback HeaderOperationCompleted;

        private System.Threading.SendOrPostCallback MenuLateralOperationCompleted;

        private System.Threading.SendOrPostCallback FooterOperationCompleted;

        private System.Threading.SendOrPostCallback HeaderInglesOperationCompleted;

        private System.Threading.SendOrPostCallback FooterENOperationCompleted;

        /// <remarks/>
        public Designer(string serviceUrl)
        {
            this.Url = serviceUrl;
        }

        /// <remarks/>
        public event HeaderCompletedEventHandler HeaderCompleted;

        /// <remarks/>
        public event MenuLateralCompletedEventHandler MenuLateralCompleted;

        /// <remarks/>
        public event FooterCompletedEventHandler FooterCompleted;

        /// <remarks/>
        public event HeaderInglesCompletedEventHandler HeaderInglesCompleted;

        /// <remarks/>
        public event FooterENCompletedEventHandler FooterENCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Header", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Header(string rutaHome, string seccion)
        {
            object[] results = this.Invoke("Header", new object[] {
                    rutaHome,
                    seccion});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginHeader(string rutaHome, string seccion, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("Header", new object[] {
                    rutaHome,
                    seccion}, callback, asyncState);
        }

        /// <remarks/>
        public string EndHeader(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void HeaderAsync(string rutaHome, string seccion)
        {
            this.HeaderAsync(rutaHome, seccion, null);
        }

        /// <remarks/>
        public void HeaderAsync(string rutaHome, string seccion, object userState)
        {
            if ((this.HeaderOperationCompleted == null))
            {
                this.HeaderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHeaderOperationCompleted);
            }
            this.InvokeAsync("Header", new object[] {
                    rutaHome,
                    seccion}, this.HeaderOperationCompleted, userState);
        }

        private void OnHeaderOperationCompleted(object arg)
        {
            if ((this.HeaderCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HeaderCompleted(this, new HeaderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MenuLateral", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MenuLateral(string RutaHome, string Urlseccion, string TituloSeccion)
        {
            object[] results = this.Invoke("MenuLateral", new object[] {
                    RutaHome,
                    Urlseccion,
                    TituloSeccion});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginMenuLateral(string RutaHome, string Urlseccion, string TituloSeccion, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("MenuLateral", new object[] {
                    RutaHome,
                    Urlseccion,
                    TituloSeccion}, callback, asyncState);
        }

        /// <remarks/>
        public string EndMenuLateral(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void MenuLateralAsync(string RutaHome, string Urlseccion, string TituloSeccion)
        {
            this.MenuLateralAsync(RutaHome, Urlseccion, TituloSeccion, null);
        }

        /// <remarks/>
        public void MenuLateralAsync(string RutaHome, string Urlseccion, string TituloSeccion, object userState)
        {
            if ((this.MenuLateralOperationCompleted == null))
            {
                this.MenuLateralOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMenuLateralOperationCompleted);
            }
            this.InvokeAsync("MenuLateral", new object[] {
                    RutaHome,
                    Urlseccion,
                    TituloSeccion}, this.MenuLateralOperationCompleted, userState);
        }

        private void OnMenuLateralOperationCompleted(object arg)
        {
            if ((this.MenuLateralCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MenuLateralCompleted(this, new MenuLateralCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Footer", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Footer()
        {
            object[] results = this.Invoke("Footer", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginFooter(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("Footer", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndFooter(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void FooterAsync()
        {
            this.FooterAsync(null);
        }

        /// <remarks/>
        public void FooterAsync(object userState)
        {
            if ((this.FooterOperationCompleted == null))
            {
                this.FooterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFooterOperationCompleted);
            }
            this.InvokeAsync("Footer", new object[0], this.FooterOperationCompleted, userState);
        }

        private void OnFooterOperationCompleted(object arg)
        {
            if ((this.FooterCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FooterCompleted(this, new FooterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HeaderIngles", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HeaderIngles(string rutaHome, string seccion)
        {
            object[] results = this.Invoke("HeaderIngles", new object[] {
                    rutaHome,
                    seccion});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginHeaderIngles(string rutaHome, string seccion, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("HeaderIngles", new object[] {
                    rutaHome,
                    seccion}, callback, asyncState);
        }

        /// <remarks/>
        public string EndHeaderIngles(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void HeaderInglesAsync(string rutaHome, string seccion)
        {
            this.HeaderInglesAsync(rutaHome, seccion, null);
        }

        /// <remarks/>
        public void HeaderInglesAsync(string rutaHome, string seccion, object userState)
        {
            if ((this.HeaderInglesOperationCompleted == null))
            {
                this.HeaderInglesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHeaderInglesOperationCompleted);
            }
            this.InvokeAsync("HeaderIngles", new object[] {
                    rutaHome,
                    seccion}, this.HeaderInglesOperationCompleted, userState);
        }

        private void OnHeaderInglesOperationCompleted(object arg)
        {
            if ((this.HeaderInglesCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HeaderInglesCompleted(this, new HeaderInglesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FooterEN", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FooterEN()
        {
            object[] results = this.Invoke("FooterEN", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginFooterEN(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("FooterEN", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndFooterEN(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void FooterENAsync()
        {
            this.FooterENAsync(null);
        }

        /// <remarks/>
        public void FooterENAsync(object userState)
        {
            if ((this.FooterENOperationCompleted == null))
            {
                this.FooterENOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFooterENOperationCompleted);
            }
            this.InvokeAsync("FooterEN", new object[0], this.FooterENOperationCompleted, userState);
        }

        private void OnFooterENOperationCompleted(object arg)
        {
            if ((this.FooterENCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FooterENCompleted(this, new FooterENCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    internal delegate void HeaderCompletedEventHandler(object sender, HeaderCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    internal partial class HeaderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal HeaderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    internal delegate void MenuLateralCompletedEventHandler(object sender, MenuLateralCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    internal partial class MenuLateralCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal MenuLateralCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    internal delegate void FooterCompletedEventHandler(object sender, FooterCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    internal partial class FooterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal FooterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    internal delegate void HeaderInglesCompletedEventHandler(object sender, HeaderInglesCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    internal partial class HeaderInglesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal HeaderInglesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    internal delegate void FooterENCompletedEventHandler(object sender, FooterENCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    internal partial class FooterENCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal FooterENCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}